# **2.B FEATURE EXTRACTION**

## Creating Final Data Set


#### This project is worked on Jupyter Notebook

In [1]:
#importing required packages for this module
import pandas as pd

In [2]:
legitimate = pd.read_csv("/Users/jillkathleen/Desktop/Phishing-Analysis-Detection/Back-End/Extracted CSVs/from FeatureExtraction/Data-2/Data-2-benign-extracted.csv")
legitimate

,domain,ip_present,at_present,url_length,url_depth,redirection,https_domain,short_url,prefix/suffix,dns_record,web_traffic,domain_age,domain_end,dot_count,specialchar_count,subdom_count,label
0,NaN,0,0,0,2,0,0,0,0,0,1,1,1,0,2,0,0
1,NaN,0,0,0,2,0,0,0,0,0,1,1,1,0,3,1,0
2,NaN,0,0,0,2,0,0,0,0,0,1,1,1,1,2,1,0
3,NaN,0,0,0,4,0,0,0,0,0,1,1,1,0,4,0,0
4,NaN,0,0,1,5,0,0,0,0,0,0,1,1,1,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4432,NaN,0,0,0,3,0,0,0,0,0,1,1,1,1,3,1,0
4433,NaN,0,0,0,2,0,0,0,0,0,1,1,1,0,2,0,0
4434,NaN,0,0,1,5,0,0,1,0,0,1,1,1,1,4,1,0
4435,NaN,0,0,0,4,0,0,0,0,0,0,1,1,1,3,0,0
4436,NaN,0,0,0,3,0,0,1,0,0,1,1,1,1,2,1,0

In [3]:
phishing = pd.read_csv("/Users/jillkathleen/Desktop/Phishing-Analysis-Detection/Back-End/Extracted CSVs/from FeatureExtraction/Data-2/D2-phish-extracted.csv")
phishing

,domain,ip_present,at_present,url_length,url_depth,redirection,https_domain,short_url,prefix/suffix,dns_record,web_traffic,domain_age,domain_end,dot_count,specialchar_count,subdom_count,label
0,doclab-console-auth.firebaseapp.com,0,0,1,2,0,0,0,1,1,1,1,1,1,5,1,1
1,voipoid.com,0,0,0,1,0,0,0,0,0,0,0,0,0,4,0,1
2,intermaticoline.com,0,0,0,1,0,0,0,0,0,1,0,1,0,4,0,1
3,alpinemountaingear.com.np,0,0,1,4,0,0,0,0,0,1,1,1,1,8,1,1
4,386f9e87.ithemeshosting.com.php73-39.lan3-1.we...,0,0,1,1,0,0,0,1,0,1,0,1,1,5,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10348,paypial-us.com,0,0,0,0,0,0,0,1,0,1,0,0,0,4,0,1
10349,dev.klinikmatanusantara.com,0,0,1,5,0,0,0,0,0,0,0,1,0,8,1,1
10350,cp.kinex11.info,0,0,1,7,0,0,0,0,0,1,0,0,1,10,1,1
10351,sieck-kuehlsysteme.de,0,1,1,4,0,0,1,1,0,1,1,1,1,10,0,1
10352,pateltutorials.com,0,1,1,3,0,0,0,0,0,0,0,1,0,9,0,1

## Final Dataset

In [4]:
#Concatenating the dataframes into one 
urls = pd.concat([legitimate, phishing]).reset_index(drop=True)

urls

,domain,ip_present,at_present,url_length,url_depth,redirection,https_domain,short_url,prefix/suffix,dns_record,web_traffic,domain_age,domain_end,dot_count,specialchar_count,subdom_count,label
0,NaN,0,0,0,2,0,0,0,0,0,1,1,1,0,2,0,0
1,NaN,0,0,0,2,0,0,0,0,0,1,1,1,0,3,1,0
2,NaN,0,0,0,2,0,0,0,0,0,1,1,1,1,2,1,0
3,NaN,0,0,0,4,0,0,0,0,0,1,1,1,0,4,0,0
4,NaN,0,0,1,5,0,0,0,0,0,0,1,1,1,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14785,paypial-us.com,0,0,0,0,0,0,0,1,0,1,0,0,0,4,0,1
14786,dev.klinikmatanusantara.com,0,0,1,5,0,0,0,0,0,0,0,1,0,8,1,1
14787,cp.kinex11.info,0,0,1,7,0,0,0,0,0,1,0,0,1,10,1,1
14788,sieck-kuehlsysteme.de,0,1,1,4,0,0,1,1,0,1,1,1,1,10,0,1
14789,pateltutorials.com,0,1,1,3,0,0,0,0,0,0,0,1,0,9,0,1

In [5]:
# Storing the data in CSV file

urls.to_csv('/Users/jillkathleen/Desktop/Phishing-Analysis-Detection/Back-End/Extracted CSVs/from FeatureExtraction/Data-2/D2-final-extracted.csv', index=False)